services:
  db:
    image: postgres:14
    container_name: task_management_system_postgres
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: tms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - provider_network

  app:
    build:
      context: .
    container_name: task_management_system_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DOCKER_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      SERVICE_URL_DEFAULT_ZONE: ${SERVICE_URL_DEFAULT_ZONE}
    volumes:
      - ./logs:/app/logs
    networks:
      - provider_network

volumes:
  pgdata:

networks:
  provider_network:
